version: '3.6'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile-ang
    ports:
      - '80:80'

  cypress:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - angular

  e2e-chrome:
    image: "cypress-test"
    environment:
        - CYPRESS_baseUrl=http://localhost:4200/
    command: ["testsmokechrome"] 
    network_mode: 'host'
    volumes:
      - ./cypress/cypress/reports_docker/chrome/videos:/var/jenkins_home/workspace/cypress_cicd/cypress/reports
      - ./cypress/cypress/reports_docker/chrome:/var/jenkins_home/workspace/cypress_cicd/cypress/reports


