version: '3.6'
services:
  e2e-chrome:
    image: "testing"   ##Docker image name
    environment:
        - CYPRESS_baseUrl=http://0.0.0.0:4200/
    command: ["testsmokechrome"] 
    network_mode: 'host'
    volumes:
      - ./cypress/cypress/reports/chrome/:/cypressdocker/cypress/reports
      
  e2e-edge:
    image: "testing"  ##Docker image name
    environment:
        - CYPRESS_baseUrl=http://0.0.0.0:4200/
    command: ["testregedge"] 
    network_mode: 'host'
    volumes:
      - ./cypress/cypress/reports/edge/:/cypressdocker/cypress/reports
    
