version: '3.6'
services:
  e2e-chrome:
    image: "cypress-test"  
    environment:
        - CYPRESS_baseUrl=https://www.youtube.com/
    command: ["testsmokechrome"] 
    network_mode: 'host'
    volumes:
      - ./cypress/cypress/reports/chrome/:/cypressdocker/cypress/reports
      
  e2e-edge:
    image: "cypress-test"  
    environment:
        - CYPRESS_baseUrl=https://www.youtube.com/
    command: ["testregedge"] 
    network_mode: 'host'
    volumes:
      - ./cypress/cypress/reports/edge/:/cypressdocker/cypress/reports
    
