version: '3.6'
services:
  e2e-chrome:
    image: "cypress-test"
    environment:
        - CYPRESS_baseUrl=http://0.0.0.0:80/
    command: ["testsmokechrome"] 
    network_mode: 'host'
    volumes:
      - ./cypress/cypress/reports_docker/chrome:/var/jenkins_home/workspace/cypress_cicd/cypress/cypress/reports


